=== 2lambda123/Common-Metadata-Repository/umm-spec-lib/resources/xml-schemas/serf/serf_v9.9.3.xsd
<?xml version="1.0" encoding="UTF-8"?>


<xs:schema  xmlns:xs="http://www.w3.org/2001/XMLSchema"
            targetNamespace="http://gcmd.gsfc.nasa.gov/Aboutus/xml/serf/"
            xmlns="http://gcmd.gsfc.nasa.gov/Aboutus/xml/serf/">

<xs:element name="SERF">
   <xs:complexType>
      <xs:sequence>
         <xs:element ref="Entry_ID" minOccurs="1" maxOccurs="1"/>
         <xs:element ref="Entry_Title" minOccurs="1" maxOccurs="1"/>
         <xs:element ref="Service_Citation" minOccurs="0" maxOccurs="unbounded"/>
         <xs:element ref="Personnel" minOccurs="0" maxOccurs="unbounded"/>
         <xs:element ref="Service_Parameters" minOccurs="1" maxOccurs="unbounded"/>
         <xs:element ref="Science_Parameters" minOccurs="1" maxOccurs="unbounded"/>
         <xs:element ref="ISO_Topic_Category" minOccurs="0" maxOccurs="unbounded"/>
         <xs:element ref="Keyword" minOccurs="0" maxOccurs="unbounded"/>
         <xs:element ref="Sensor_Name" minOccurs="0" maxOccurs="unbounded"/>
         <xs:element ref="Source_Name" minOccurs="0" maxOccurs="unbounded"/>
         <xs:element ref="Project" minOccurs="0" maxOccurs="unbounded"/>
         <xs:element ref="Quality" minOccurs="0" maxOccurs="1"/>
         <xs:element ref="Access_Constraints" minOccurs="0" maxOccurs="1"/>
         <xs:element ref="Use_Constraints" minOccurs="0" maxOccurs="1"/>
         <xs:element ref="Service_Language" minOccurs="0" maxOccurs="unbounded"/>
         <xs:element ref="Distribution" minOccurs="0" maxOccurs="unbounded"/>
         <xs:element ref="Multimedia_Sample" minOccurs="0" maxOccurs="unbounded"/>
         <xs:element ref="Reference" minOccurs="0" maxOccurs="unbounded"/>
         <xs:element ref="Service_Provider" minOccurs="1" maxOccurs="unbounded"/>
         <xs:element ref="Summary" minOccurs="1" maxOccurs="1"/>
         <xs:element ref="Related_URL" minOccurs="0" maxOccurs="unbounded"/>
         <xs:element ref="Parent_SERF" minOccurs="0" maxOccurs="unbounded"/>
         <xs:element ref="IDN_Node" minOccurs="0" maxOccurs="unbounded"/>
         <xs:element ref="Metadata_Name" minOccurs="1" maxOccurs="1"/>
         <xs:element ref="Metadata_Version" minOccurs="1" maxOccurs="1"/>
         <xs:element ref="SERF_Creation_Date" minOccurs="0" maxOccurs="1"/>
         <xs:element ref="Last_SERF_Revision_Date" minOccurs="0" maxOccurs="1"/>
         <xs:element ref="SERF_Revision_History" minOccurs="0" maxOccurs="1"/>
         <xs:element ref="Future_SERF_Review_Date" minOccurs="0" maxOccurs="1"/>
         <xs:element ref="Private" minOccurs="0" maxOccurs="1"/>
         <xs:element ref="Extended_Metadata" minOccurs="0" maxOccurs="unbounded"/>
      </xs:sequence>
   </xs:complexType>
</xs:element>
<xs:element name="Entry_ID" type="xs:string"/>
<xs:element name="Entry_Title" type="xs:string"/>
<xs:element name="Service_Citation">
   <xs:complexType>
      <xs:sequence>
         <xs:element ref="Originators" minOccurs="0" maxOccurs="1"/>
         <xs:element ref="Title" minOccurs="0" maxOccurs="1"/>
         <xs:element ref="Release_Date" minOccurs="0" maxOccurs="1"/>
         <xs:element ref="Provider" minOccurs="0" maxOccurs="1"/>
         <xs:element ref="Edition" minOccurs="0" maxOccurs="1"/>
         <xs:element ref="URL" minOccurs="0" maxOccurs="1"/>
      </xs:sequence>
   </xs:complexType>
</xs:element>
<xs:element name="Originators" type="xs:string"/>
<xs:element name="Title" type="xs:string"/>
<xs:element name="Release_Date" type="xs:string"/>
<xs:element name="Provider" type="xs:string"/>
<xs:element name="Edition" type="xs:string"/>
<xs:element name="URL" type="xs:string"/>
<xs:element name="Personnel">
   <xs:complexType>
      <xs:sequence>
         <xs:element ref="Role" minOccurs="1" maxOccurs="unbounded"/>
         <xs:element ref="First_Name" minOccurs="0" maxOccurs="1"/>
         <xs:element ref="Middle_Name" minOccurs="0" maxOccurs="1"/>
         <xs:element ref="Last_Name" minOccurs="1" maxOccurs="1"/>
         <xs:element ref="Email" minOccurs="0" maxOccurs="unbounded"/>
         <xs:element ref="Phone" minOccurs="0" maxOccurs="unbounded"/>
         <xs:element ref="Fax" minOccurs="0" maxOccurs="unbounded"/>
         <xs:element ref="Contact_Address" minOccurs="0" maxOccurs="1"/>
      </xs:sequence>
   </xs:complexType>
</xs:element>
<xs:element name="Role" type="xs:string"/>
<xs:element name="First_Name" type="xs:string"/>
<xs:element name="Middle_Name" type="xs:string"/>
<xs:element name="Last_Name" type="xs:string"/>
<xs:element name="Email" type="xs:string"/>
<xs:element name="Phone" type="xs:string"/>
<xs:element name="Fax" type="xs:string"/>
<xs:element name="FAX" type="xs:string"/>
<xs:element name="Contact_Address">
   <xs:complexType>
      <xs:sequence>
         <xs:element ref="Address" minOccurs="0" maxOccurs="unbounded"/>
         <xs:element ref="City" minOccurs="0" maxOccurs="1"/>
         <xs:element ref="Province_or_State" minOccurs="0" maxOccurs="1"/>
         <xs:element ref="Postal_Code" minOccurs="0" maxOccurs="1"/>
         <xs:element ref="Country" minOccurs="0" maxOccurs="1"/>
      </xs:sequence>
   </xs:complexType>
</xs:element>
<xs:element name="Address" type="xs:string"/>
<xs:element name="City" type="xs:string"/>
<xs:element name="Province_or_State" type="xs:string"/>
<xs:element name="Postal_Code" type="xs:string"/>
<xs:element name="Country" type="xs:string"/>
<xs:element name="Service_Parameters">
   <xs:complexType>
      <xs:sequence>
         <xs:element ref="Service_Category" minOccurs="1" maxOccurs="1"/>
         <xs:element ref="Service_Topic" minOccurs="1" maxOccurs="1"/>
         <xs:element ref="Service_Term" minOccurs="1" maxOccurs="1"/>
         <xs:element ref="Service_Specific_Name" minOccurs="0" maxOccurs="1"/>
      </xs:sequence>
      <xs:attribute name="uuid" type="xs:string"/>
   </xs:complexType>
</xs:element>
<xs:element name="Service_Category" type="xs:string"/>
<xs:element name="Service_Topic" type="xs:string"/>
<xs:element name="Service_Term" type="xs:string"/>
<xs:element name="Service_Specific_Name" type="xs:string"/>
<xs:element name="Science_Parameters">
   <xs:complexType>
      <xs:sequence>
         <xs:element ref="Science_Category" minOccurs="1" maxOccurs="1"/>
         <xs:element ref="Science_Topic" minOccurs="1" maxOccurs="1"/>
         <xs:element ref="Science_Term" minOccurs="1" maxOccurs="1"/>
         <xs:element ref="Science_Variable_Level_1" minOccurs="0" maxOccurs="1"/>
         <xs:element ref="Science_Variable_Level_2" minOccurs="0" maxOccurs="1"/>
         <xs:element ref="Science_Variable_Level_3" minOccurs="0" maxOccurs="1"/>
         <xs:element ref="Science_Detailed_Variable" minOccurs="0" maxOccurs="1"/>
      </xs:sequence>
      <xs:attribute name="uuid" type="xs:string"/>
   </xs:complexType>
</xs:element>
<xs:element name="Science_Category" type="xs:string"/>
<xs:element name="Science_Topic" type="xs:string"/>
<xs:element name="Science_Term" type="xs:string"/>
<xs:element name="Science_Variable_Level_1" type="xs:string"/>
<xs:element name="Science_Variable_Level_2" type="xs:string"/>
<xs:element name="Science_Variable_Level_3" type="xs:string"/>
<xs:element name="Science_Detailed_Variable" type="xs:string"/>
<xs:element name="ISO_Topic_Category">
        <xs:complexType>
                <xs:simpleContent>
                        <xs:extension base="xs:string">
                                <xs:attribute name="uuid" type="xs:string"/>
                        </xs:extension>
                </xs:simpleContent>
        </xs:complexType>
</xs:element>
<xs:element name="Keyword" type="xs:string"/>
<xs:element name="Sensor_Name">
   <xs:complexType>
      <xs:sequence>
         <xs:element ref="Short_Name" minOccurs="1" maxOccurs="1"/>
         <xs:element ref="Long_Name" minOccurs="0" maxOccurs="1"/>
      </xs:sequence>
      <xs:attribute name="uuid" type="xs:string"/>
   </xs:complexType>
</xs:element>
<xs:element name="Short_Name" type="xs:string"/>
<xs:element name="Long_Name" type="xs:string"/>
<xs:element name="Source_Name">
   <xs:complexType>
      <xs:sequence>
         <xs:element ref="Short_Name" minOccurs="1" maxOccurs="1"/>
         <xs:element ref="Long_Name" minOccurs="0" maxOccurs="1"/>
      </xs:sequence>
      <xs:attribute name="uuid" type="xs:string"/>
   </xs:complexType>
</xs:element>
<xs:element name="Project">
   <xs:complexType>
      <xs:sequence>
         <xs:element ref="Short_Name" minOccurs="1" maxOccurs="1"/>
         <xs:element ref="Long_Name" minOccurs="0" maxOccurs="1"/>
      </xs:sequence>
      <xs:attribute name="uuid" type="xs:string"/>
   </xs:complexType>
</xs:element>
<xs:element name="Quality" type="xs:string"/>
<xs:element name="Access_Constraints" type="xs:string"/>
<xs:element name="Use_Constraints" type="xs:string"/>
<xs:element name="Service_Language" type="xs:string"/>
<xs:element name="Distribution">
   <xs:complexType>
      <xs:sequence>
         <xs:element ref="Distribution_Media" minOccurs="0" maxOccurs="1"/>
         <xs:element ref="Distribution_Size" minOccurs="0" maxOccurs="1"/>
         <xs:element ref="Distribution_Format" minOccurs="0" maxOccurs="1"/>
         <xs:element ref="Fees" minOccurs="0" maxOccurs="1"/>
      </xs:sequence>
   </xs:complexType>
</xs:element>
<xs:element name="Distribution_Media" type="xs:string"/>
<xs:element name="Distribution_Size" type="xs:string"/>
<xs:element name="Distribution_Format" type="xs:string"/>
<xs:element name="Fees" type="xs:string"/>
<xs:element name="Multimedia_Sample">
   <xs:complexType>
      <xs:sequence>
         <xs:element ref="File" minOccurs="0" maxOccurs="1"/>
         <xs:element ref="URL" minOccurs="0" maxOccurs="1"/>
         <xs:element ref="Format" minOccurs="0" maxOccurs="1"/>
         <xs:element ref="Caption" minOccurs="0" maxOccurs="1"/>
         <xs:element ref="Description" minOccurs="0" maxOccurs="1"/>
      </xs:sequence>
   </xs:complexType>
</xs:element>
<xs:element name="File" type="xs:string"/>
<xs:element name="Format" type="xs:string"/>
<xs:element name="Caption" type="xs:string"/>
<xs:element name="Description" type="xs:string"/>

<xs:element name="Reference">
   <xs:complexType mixed="true">
      <xs:sequence>
         <xs:element ref="Author" minOccurs="0" maxOccurs="1"/>
         <xs:element ref="Publication_Date" minOccurs="0" maxOccurs="1"/>
         <xs:element ref="Title" minOccurs="0" maxOccurs="1"/>
         <xs:element ref="Series" minOccurs="0" maxOccurs="1"/>
         <xs:element ref="Edition" minOccurs="0" maxOccurs="1"/>
         <xs:element ref="Volume" minOccurs="0" maxOccurs="1"/>
         <xs:element ref="Issue" minOccurs="0" maxOccurs="1"/>
         <xs:element ref="Report_Number" minOccurs="0" maxOccurs="1"/>
         <xs:element ref="Publication_Place" minOccurs="0" maxOccurs="1"/>
         <xs:element ref="Publisher" minOccurs="0" maxOccurs="1"/>
         <xs:element ref="Pages" minOccurs="0" maxOccurs="1"/>
         <xs:element ref="ISBN" minOccurs="0" maxOccurs="1"/>
         <xs:element ref="DOI" minOccurs="0" maxOccurs="1"/>
         <xs:element ref="Online_Resource" minOccurs="0" maxOccurs="1"/>
         <xs:element ref="Other_Reference_Details" minOccurs="0" maxOccurs="1"/>
      </xs:sequence>
   </xs:complexType>
</xs:element>   
<xs:element name="Author" type="xs:string"/>
<xs:element name="Publication_Date" type="xs:string"/>
<xs:element name="Series" type="xs:string"/>
<xs:element name="Volume" type="xs:string"/>
<xs:element name="Issue" type="xs:string"/>
<xs:element name="Report_Number" type="xs:string"/>
<xs:element name="Publication_Place" type="xs:string"/>
<xs:element name="Publisher" type="xs:string"/>
<xs:element name="Pages" type="xs:string"/>
<xs:element name="ISBN" type="xs:string"/>
<xs:element name="DOI" type="xs:string"/>
<xs:element name="Online_Resource" type="xs:string"/>
<xs:element name="Other_Reference_Details" type="xs:string"/>

<xs:element name="Service_Provider">
   <xs:complexType>
      <xs:sequence>
         <xs:element ref="Service_Organization" minOccurs="1" maxOccurs="1"/>
         <xs:element ref="Service_Organization_URL" minOccurs="0" maxOccurs="1"/>
         <xs:element ref="Personnel" minOccurs="1" maxOccurs="unbounded"/>
      </xs:sequence>
      <xs:attribute name="uuid" type="xs:string"/>
   </xs:complexType>
</xs:element>
<xs:element name="Service_Organization">
   <xs:complexType>
      <xs:sequence>
         <xs:element ref="Short_Name" minOccurs="1" maxOccurs="1"/>
         <xs:element ref="Long_Name" minOccurs="0" maxOccurs="1"/>
      </xs:sequence>
      <xs:attribute name="uuid" type="xs:string"/>
   </xs:complexType>
</xs:element>
<xs:element name="Service_Organization_URL" type="xs:string"/>

<xs:element name="Summary">
   <xs:complexType mixed="true">
      <xs:sequence>
         <xs:element ref="Abstract" minOccurs="0" maxOccurs="1"/>
         <xs:element ref="Purpose" minOccurs="0" maxOccurs="1"/>
      </xs:sequence>
   </xs:complexType>
</xs:element>
<xs:element name="Abstract" type="xs:string"/>
<xs:element name="Purpose" type="xs:string"/>

<xs:element name="Related_URL">
   <xs:complexType>
      <xs:sequence>
         <xs:element ref="URL_Content_Type" minOccurs="0" maxOccurs="1"/>
         <xs:element ref="URL" minOccurs="1" maxOccurs="unbounded"/>
         <xs:element ref="Description" minOccurs="0" maxOccurs="1"/>
      </xs:sequence>
   </xs:complexType>
</xs:element>

<xs:element name="URL_Content_Type">
   <xs:complexType>
      <xs:sequence>
         <xs:element ref="Type" minOccurs="1" maxOccurs="1"/>
         <xs:element ref="Subtype" minOccurs="0" maxOccurs="1"/>
      </xs:sequence>
      <xs:attribute name="uuid" type="xs:string"/>
   </xs:complexType>
</xs:element>
<xs:element name="Type" type="xs:string"/>
<xs:element name="Subtype" type="xs:string"/>

<xs:element name="Parent_SERF" type="xs:string"/>
<xs:element name="IDN_Node">
   <xs:complexType>
      <xs:sequence>
         <xs:element ref="Short_Name" minOccurs="1" maxOccurs="1"/>
         <xs:element ref="Long_Name" minOccurs="0" maxOccurs="1"/>
      </xs:sequence>
      <xs:attribute name="uuid" type="xs:string"/>
   </xs:complexType>
</xs:element>
<xs:element name="Metadata_Name" type="xs:string"/>
<xs:element name="Metadata_Version" type="xs:string"/>
<xs:element name="SERF_Creation_Date" type="xs:string"/>
<xs:element name="Last_SERF_Revision_Date" type="xs:string"/>
<xs:element name="SERF_Revision_History" type="xs:string"/>
<xs:element name="Future_SERF_Review_Date" type="xs:string"/>
<xs:element name="Private" type="xs:string"/>

<xs:element name="Extended_Metadata">
   <xs:complexType>
      <xs:sequence>
         <xs:element ref="Metadata" minOccurs="1" maxOccurs="unbounded"/>
      </xs:sequence>
   </xs:complexType>
</xs:element>

<xs:element name="Metadata">
    <xs:complexType>
        <xs:sequence>
            <xs:element ref="Group" minOccurs="0" maxOccurs="1"/>
            <xs:element ref="Name" minOccurs="1" maxOccurs="1"/>
            <xs:element ref="Description" minOccurs="0" maxOccurs="1"/>
            <xs:element ref="Type" minOccurs="0" maxOccurs="1"/>
            <xs:element ref="Update_Date" minOccurs="0" maxOccurs="1"/>
            <xs:element ref="Value" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>
</xs:element>

<xs:element name="Group" type="xs:string"/>
<xs:element name="Name" type="xs:string"/>
<xs:element name="Update_Date" type="xs:string"/>

<xs:element name="Value">
    <xs:complexType>
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute type="xs:string" name="type"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>
</xs:element>

</xs:schema>

=== 2lambda123/Common-Metadata-Repository/umm-spec-lib/resources/example_data/serf.xml
<?xml version="1.0" encoding="UTF-8"?>
<SERF xmlns="http://gcmd.gsfc.nasa.gov/Aboutus/xml/serf/" xmlns:serf="http://gcmd.gsfc.nasa.gov/Aboutus/xml/serf/" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://gcmd.gsfc.nasa.gov/Aboutus/xml/serf/ http://gcmd.gsfc.nasa.gov/Aboutus/xml/serf/serf_v9.9.3.xsd">
  <Entry_ID>NASA_GES_DISC_AIRS_Atmosphere_Data_Web_Coverage_Service</Entry_ID>
  <Entry_Title>OGC Web Coverage Service (WCS) for accessing Atmospheric Infrared Sounder (AIRS) Data</Entry_Title>
  <Service_Citation>
    <Originators>NASA Goddard Earth Sciences (GES) Data and Information Services Center (DISC)</Originators>
    <Title>OGC Web Coverage Service (WCS) for accessing Atmospheric Infrared Sounder (AIRS) Data</Title>
  </Service_Citation>
  <Personnel>
    <Role>TECHNICAL CONTACT</Role>
    <Role>SERF AUTHOR</Role>
    <First_Name>FIRSTNAME</First_Name>
    <Last_Name>LASTNAME</Last_Name>
    <Email>FIRSTNAME.LASTNAME@nasa.gov</Email>
    <Phone>301-555-5555</Phone>
    <Phone>301-777-5555</Phone>
    <Fax>301-555-5678</Fax>
    <Contact_Address>
      <Address>NASA/GSFC Code 610.2</Address>
      <City>Greenbelt</City>
      <Province_or_State>Maryland</Province_or_State>
      <Postal_Code>20771</Postal_Code>
      <Country>USA</Country>
    </Contact_Address>
  </Personnel>
  <Service_Parameters uuid="617a50aa-5762-4ff3-aa03-c94b5cc65209">
    <Service_Category>EARTH SCIENCE SERVICES</Service_Category>
    <Service_Topic>WEB SERVICES</Service_Topic>
    <Service_Term>DATA APPLICATION SERVICES</Service_Term>
    <Service_Specific_Name>GEOGRAPHIC DATA EXTRACTION SERVICES</Service_Specific_Name>
  </Service_Parameters>
  <Service_Parameters uuid="62d7c667-997a-4a9d-abe1-4cca4519673e">
    <Service_Category>EARTH SCIENCE SERVICES</Service_Category>
    <Service_Topic>WEB SERVICES</Service_Topic>
    <Service_Term>DATA APPLICATION SERVICES</Service_Term>
    <Service_Specific_Name>COVERAGE GENERALIZATION SERVICES</Service_Specific_Name>
  </Service_Parameters>
  <Service_Parameters uuid="91e02d43-bf56-480f-89c9-ddfca7fc7239">
    <Service_Category>EARTH SCIENCE SERVICES</Service_Category>
    <Service_Topic>WEB SERVICES</Service_Topic>
    <Service_Term>DATA PROCESSING SERVICES</Service_Term>
    <Service_Specific_Name>COVERAGE GENERALIZATION SERVICES</Service_Specific_Name>
  </Service_Parameters>
  <Service_Parameters uuid="d6379bf5-88dd-4ec0-9b15-441db5b10b59">
    <Service_Category>EARTH SCIENCE SERVICES</Service_Category>
    <Service_Topic>WEB SERVICES</Service_Topic>
    <Service_Term>INFORMATION MANAGEMENT SERVICES</Service_Term>
    <Service_Specific_Name>WEB COVERAGE SERVICE</Service_Specific_Name>
  </Service_Parameters>
  <Science_Parameters uuid="2e5a401b-1507-4f57-82b8-36557c13b154">
    <Science_Category>EARTH SCIENCE</Science_Category>
    <Science_Topic>ATMOSPHERE</Science_Topic>
    <Science_Term>AEROSOLS</Science_Term>
  </Science_Parameters>
  <Science_Parameters uuid="77397026-09c9-44e0-b85f-77b2bc9b1630">
    <Science_Category>EARTH SCIENCE</Science_Category>
    <Science_Topic>ATMOSPHERE</Science_Topic>
    <Science_Term>AIR QUALITY</Science_Term>
  </Science_Parameters>
  <Science_Parameters uuid="b9c56939-c624-467d-b196-e56a5b660334">
    <Science_Category>EARTH SCIENCE</Science_Category>
    <Science_Topic>ATMOSPHERE</Science_Topic>
    <Science_Term>ATMOSPHERIC CHEMISTRY</Science_Term>
  </Science_Parameters>
  <Science_Parameters uuid="35e1f93b-99b3-4430-b477-0ecafa80d67a">
    <Science_Category>EARTH SCIENCE</Science_Category>
    <Science_Topic>ATMOSPHERE</Science_Topic>
    <Science_Term>ATMOSPHERIC TEMPERATURE</Science_Term>
  </Science_Parameters>
  <Science_Parameters uuid="286d2ae0-9d86-4ef0-a2b4-014843a98532">
    <Science_Category>EARTH SCIENCE</Science_Category>
    <Science_Topic>ATMOSPHERE</Science_Topic>
    <Science_Term>ATMOSPHERIC WATER VAPOR</Science_Term>
  </Science_Parameters>
  <Science_Parameters uuid="df160e31-ae45-41a4-9093-a80fe5303cea">
    <Science_Category>EARTH SCIENCE</Science_Category>
    <Science_Topic>ATMOSPHERE</Science_Topic>
    <Science_Term>ATMOSPHERIC WINDS</Science_Term>
  </Science_Parameters>
  <Science_Parameters uuid="162e2243-3266-4999-b352-d8a1a9dc82ac">
    <Science_Category>EARTH SCIENCE</Science_Category>
    <Science_Topic>ATMOSPHERE</Science_Topic>
    <Science_Term>CLOUDS</Science_Term>
  </Science_Parameters>
  <Science_Parameters uuid="1532e590-a62d-46e3-8d03-2351bc48166a">
    <Science_Category>EARTH SCIENCE</Science_Category>
    <Science_Topic>ATMOSPHERE</Science_Topic>
    <Science_Term>PRECIPITATION</Science_Term>
  </Science_Parameters>
  <Science_Parameters uuid="4ad0c52d-6449-48ff-8678-adc6b2cebcb7">
    <Science_Category>EARTH SCIENCE</Science_Category>
    <Science_Topic>ATMOSPHERE</Science_Topic>
    <Science_Term>ATMOSPHERIC RADIATION</Science_Term>
  </Science_Parameters>
  <Science_Parameters uuid="08fd82a1-4370-46a2-82ea-94c0f91498a7">
    <Science_Category>EARTH SCIENCE</Science_Category>
    <Science_Topic>ATMOSPHERE</Science_Topic>
    <Science_Term>ATMOSPHERIC PRESSURE</Science_Term>
  </Science_Parameters>
  <ISO_Topic_Category uuid="1ebf71bd-d007-42f8-8f9b-8c44a6b65a28">CLIMATOLOGY/METEOROLOGY/ATMOSPHERE</ISO_Topic_Category>
  <ISO_Topic_Category uuid="81a52fa1-4a8f-4c4d-9736-7aaf0859df9d">ENVIRONMENT</ISO_Topic_Category>
  <ISO_Topic_Category uuid="26ebb539-cae2-4961-9252-7f367642fa57">IMAGERY/BASE MAPS/EARTH COVER</ISO_Topic_Category>
  <Sensor_Name uuid="3a45d262-7ff0-4f69-8e31-48f56a7edb82">
    <Short_Name>AEM</Short_Name>
    <Long_Name>Airborne Electromagnetic Profiler</Long_Name>
  </Sensor_Name>
  <Sensor_Name uuid="a9bd961e-1063-4f37-99b6-ecd77aa9eb40">
    <Short_Name>AIRS</Short_Name>
    <Long_Name>Atmospheric Infrared Sounder</Long_Name>
  </Sensor_Name>
  <Sensor_Name uuid="30926fb0-7796-4ac1-9d8e-7cd1e4a4b7d1">
    <Short_Name>AERS</Short_Name>
    <Long_Name>Atmospheric/Emitted Radiation Sensor</Long_Name>
  </Sensor_Name>
  <Source_Name uuid="ea7fd15d-190d-43f3-bdd3-75f5d88dc3f8">
    <Short_Name>AQUA</Short_Name>
    <Long_Name>Earth Observing System, AQUA</Long_Name>
  </Source_Name>
  <Project uuid="3d1847aa-4eba-4c78-b4fc-f4223ca16539">
    <Short_Name>EOS</Short_Name>
    <Long_Name>Earth Observing System</Long_Name>
  </Project>
  <Project uuid="4dac8541-0c69-4cd5-ae70-eb8819f39715">
    <Short_Name>EOSDIS</Short_Name>
    <Long_Name>Earth Observing System Data Information System</Long_Name>
  </Project>
  <Project uuid="5f139d40-4050-4a8e-bd2b-fcae1cfe3d01">
    <Short_Name>ESIP</Short_Name>
    <Long_Name>Earth Science Information Partners Program</Long_Name>
  </Project>
  <Project uuid="c9c09e63-c018-4870-b0cd-fcc37a2539a8">
    <Short_Name>OGC/WCS</Short_Name>
    <Long_Name>Open Geospatial Consortium/Web Coverage Service</Long_Name>
  </Project>
  <Service_Language>English</Service_Language>
  <Distribution>
    <Distribution_Media>Digital</Distribution_Media>
    <Distribution_Size>&lt;=728MB per request</Distribution_Size>
    <Distribution_Format>HTTP</Distribution_Format>
    <Fees>None</Fees>
  </Distribution>
  <Service_Provider>
    <Service_Organization uuid="51a7f454-defc-47c2-ba6a-f95847962b7e">
      <Short_Name>NASA/GSFC/SED/ESD/GCDC/GESDISC</Short_Name>
      <Long_Name>Goddard Earth Sciences Data and Information Services Center (formerly Goddard DAAC), Global Change Data Center, Earth Sciences Division, Science and Exploration Directorate, Goddard Space Flight Center, NASA</Long_Name>
    </Service_Organization>
    <Service_Organization_URL>http://disc.gsfc.nasa.gov/</Service_Organization_URL>
    <Personnel>
      <Role>SERVICE PROVIDER CONTACT</Role>
      <First_Name>FIRSTNAME</First_Name>
      <Last_Name>LASTNAME</Last_Name>
      <Email>FIRSTNAME.LASTNAME@nasa.gov</Email>
      <Phone>301-555-5555</Phone>
      <Fax>301-555-5555</Fax>
      <Contact_Address>
        <Address>NASA GSFC, Code 610.2</Address>
        <City>Greenbelt</City>
        <Province_or_State>MD</Province_or_State>
        <Postal_Code>20771</Postal_Code>
        <Country>U.S.A.</Country>
      </Contact_Address>
    </Personnel>
  </Service_Provider>
  <Summary>
    <Abstract>This is one of the GES DISC's OGC Web Coverage Service (WCS) instances which provides Level 3 Gridded atmospheric data products derived from the Atmospheric Infrared Sounder (AIRS) on board NASA's Aqua spacecraft.</Abstract>
  </Summary>
  <Related_URL>
    <URL_Content_Type uuid="029540bb-7f5c-44ba-8578-61e2f858be60">
      <Type>GET SERVICE</Type>
      <Subtype>GET WEB COVERAGE SERVICE (WCS)</Subtype>
    </URL_Content_Type>
    <URL>http://acdisc.sci.gsfc.nasa.gov/daac-bin/wcsAIRSL3?Service=WCS&amp;Version=1.0.0&amp;Request=getCapabilities</URL>
    <Description>This Web Coverage Service (WCS) is one of the multiple GES DISC data service instances used to provide gridded Level 3 Atmospheric Infrared Sounder (AIRS) data products. Accessing to this URL will result in a brief description of coverages (i.e., data layers or variables), or a getCapabilities response. A client can request more detailed information about the served coverages by sending a describeCoverage request to the server. Finally, a client can request actual data using a getCoverage request. </Description>
  </Related_URL>
  <Parent_SERF>Test Parent SERF V 5</Parent_SERF>
  <IDN_Node uuid="9ae20472-ba4c-4b01-8d97-857b73fa3c95">
    <Short_Name>USA/NASA</Short_Name>
    <Long_Name>Test Node 123</Long_Name>
  </IDN_Node>
  <IDN_Node uuid="9ae20472-ba4c-4b01-8d97-857b73fa3283">
    <Short_Name>USA/CWIC</Short_Name>
    <Long_Name>Test Node 456</Long_Name>
  </IDN_Node>
  <Metadata_Name>CEOS IDN SERF</Metadata_Name>
  <Metadata_Version>VERSION 9.7.1</Metadata_Version>
  <SERF_Creation_Date>2009-12-03</SERF_Creation_Date>
  <Last_SERF_Revision_Date>2009-12-04</Last_SERF_Revision_Date>
  <Extended_Metadata>
    <Metadata>
      <Group>gov.nasa.gsfc.gcmd</Group>
      <Name>metadata.extraction_date</Name>
